FROM  nvcr.io/nvidia/pytorch:22.07-py3
#
COPY ./requirements.txt /workspace/requirements.txt
COPY . /workspace/glados-tts/
COPY run.sh /workspace/glados-tts

ENV TZ=America/Boise
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update 
RUN apt-get install -y tzdata
RUN apt-get -y install espeak 
RUN mkdir -p /workspace/glados-tts/audio 
RUN pip install -r requirements.txt 
RUN chmod +x /workspace/glados-tts/run.sh

CMD ["/workspace/glados-tts/run.sh"]
