FROM  nvcr.io/nvidia/pytorch:22.07-py3
#
COPY ./requirements.txt /workspace/requirements.txt
COPY . /workspace/glados-tts/

RUN apt-get update && \
apt-get -y install espeak && \
mkdir -p workspace/glados-tts/audio && \
pip install -r requirements.txt

CMD ["/workspace/glados-tts/run.sh"]
